### ISSUE TITLE
Mm

### ISSUE THREAD

**Issue by Yusufibin** [ignir-arch/facebook_hack#2]
Je sais pas ce que tu voulais faire mais c'est méchant

**Comment by ignir-arch** [comment]
@Yusufibin Rien à foutre eft...

**Comment by Yusufibin** [comment]
Non mais sérieux... .

**Comment by ignir-arch** [comment]
@Yusufibin Okey.

**Comment by ignir-arch** [comment]
@ignir-arch Je m'en fiche
